# Use an official Node.js runtime as a parent image
FROM node:18-alpine
# Set the working directory in the container
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
# We do this separately to leverage Docker cache for dependencies
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy the rest of the application code
COPY . .
# Expose the port your Node.js app listens on
EXPOSE 5000
# Define the command to run your app
CMD ["npm", "start"]